### ISSUE TITLE
Is this a bug that implementation contains something related to timings?

### ISSUE THREAD

**Issue by s1ddok** [b0nes164/GPUPrefixSums#10]
I noticed [this](https://github.com/b0nes164/GPUPrefixSums/blob/a087698347cd1d0af16f02f93c1acb644ea71904/src/MainPrefixSums/DeviceLevelPrefixSums/ChainedScanWithDecoupledLookbackInclusive.compute#L349), is it a leftover from timing implementation? doesn't seem necessary.

**Comment by b0nes164** [comment]
Good eye, but this is for the new timing method. To the best of my knowledge, HLSL does not have a way to time kernels "on GPU", so we have to time the kernel execution from the CPU side. To do this, we make an [`AsyncGPUReadback.Request`](https://docs.unity3d.com/ScriptReference/Rendering.AsyncGPUReadback.html) on a buffer that we are using like so:
https://github.com/b0nes164/GPUPrefixSums/blob/a087698347cd1d0af16f02f93c1acb644ea71904/src/MainPrefixSums/DeviceLevelPrefixSums/ChainedScanWithDecoupledLookbackInclusive.cs#L323

 The issue is that an `AsyncGPUReadback.Request` essentially waits for a kernel to finish, then reads **the entire** buffer back into CPU memory. While this does time the execution of the kernel, reading data from CPU to GPU is **extremely** slow, and the latency introduced by this will obfuscate the true execution time for the kernel. For example at an input size of 2^28 the estimated runtime of the algorithm on my 2080 Super is somewhere around ~0.005 seconds. Based on my own testing, at this input size the readback takes ~**.67** seconds which completely messes up the data.
 
 To get around this, we create `b_timing` **just** so we can use it as the target of the `AsyncGPUReadback.Request`. Because it has negligible size, the latency introduced by the readback is basically irrelevant.
 
 But you're absolutely right, it's strictly unnecessary to the execution of _Chained Scan with Decoupled Lookback_.

**Comment by s1ddok** [comment]
thank you for a very elaborated answer! i will remove those lines from my implementation then
