### ISSUE TITLE
The purpose of b_index

### ISSUE THREAD

**Issue by s1ddok** [b0nes164/GPUPrefixSums#11]
Can you explain the purpose of a b_index?

**Comment by b0nes164** [comment]
This one will be a little complicated. 

First, let us assume that there are more partition tiles than the maximum number of threadblocks which can be hosted on the GPU.  Given that there are $\frac{inputSize}{partitionTileSize}$ partition tiles, and we use a partition tile of size 8192, this is almost always true.

Now let's take a look at the *lookback* phase of the algorithm:
https://github.com/b0nes164/GPUPrefixSums/blob/a087698347cd1d0af16f02f93c1acb644ea71904/src/MainPrefixSums/DeviceLevelPrefixSums/ChainedScanWithDecoupledLookBackExclusive.compute#L357-L392

Each partition tile is serially dependent on the reduced sum of *all* preceding partition tiles. During the *lookback* phase we essentially create a threadblock level spin-lock that spins until all preceding sums have been posted in `b_state`. However, recall that GPU is free to schedule the execution of threadblocks in ***any order it wants.*** So for example, for 100 scheduled threadblocks a possible execution order is: threadblock 100, threadblock 51, threadblock 67 . . . Furthermore, in programming environments like HLSL or Metal, threadblocks follow the ***occupancy bound execution model.*** Basically, once a threadblock begins executing on an SM, it ***must run to completion.*** 

So here is the problem: Say we have 100 partition tiles, but our GPU can host a maximum of 32 threadblocks. If we use the `SV_GroupID` to assign partition tiles, e.g. threadblock 0 processes partition tile 0, threadblock 1 processes partition tile 1 and so on, there is a chance that the GPU is completely occupied by threadblocks that each have a preceding partition tile that has not been processed or begun being processed. ***Because our spin-lock only unlocks when all preceding sums are posted, this results in a deadlock. Because of the occupancy bound execution model, the GPU can't switch to a new threadblock if one is stalled.*** This crashes the kernel.

So going back to our example, imagine we begin execution of our algorithm and our GPU begins executing threadblocks 10 to 41 which each begin processing their corresponding partition tile. However, they're each dependent on the partition tiles 0 to 9, and upon entering the lookback phase begin waiting for those sums to be posted. Because of the occupancy bound execution model, the GPU can't switch execution to threadblocks 0 to 9, and so the threadblocks spin until the kernel crashes.

The solution to this is quite clever. Instead of assigning partition tiles by `SV_GroupID`, we initialize a single index in device memory to `0`. This is `b_index`. Upon beginning execution, each threadblock atomically fetches and increments `b_index`, like so:
https://github.com/b0nes164/GPUPrefixSums/blob/a087698347cd1d0af16f02f93c1acb644ea71904/src/MainPrefixSums/DeviceLevelPrefixSums/ChainedScanWithDecoupledLookBackExclusive.compute#L114-L118

The value fetched from `b_index` is the partition tile that will be processed, and by incrementing `b_index` by 1, it signals that the tile has begun being processed. So for example:

+ `b_index` is initialized to 0.

+ threadblock 99 begins execution, fetches 0 and increments by 1. Begins processing partition tile 0.

+ threadblock 26 begins execution, fetches 1 and increments by 1. Begins processing partition tile 1.

+ threadblock 53 begins execution, fetches 2 and increments by 1. Begins processing partition tile 2.

By assigning partition tiles this way, ***you guarantee that no threadblock begins execution of a partition tile with preceding partition tiles that have not been processed or begun being processed. And because of that, you guarantee that the deadlock cannot occur.

**Comment by s1ddok** [comment]
wow, thank you!

I believe it is worth being copied to the readme!

though is it really any order of threadgroup scheduling? is it explicitly stated anywhere in DirectX/Metal docs that threadgroups can be launched with IDs discrepancy larger than GPUs capacity of threadgroups of given size? I think it is reasonable to launch threadgroups more or less serially, at least in terms of data caching so why would vendors implement that much of a random scheduling?

**Comment by b0nes164** [comment]
> is it explicitly stated anywhere in DirectX/Metal docs that threadgroups can be launched with IDs discrepancy larger than GPUs capacity of threadgroups of given size? 

Although I do not have the documentation on hand to reference this, yes you can quite explicitly schedule as many threadblocks as you want. This is because the factors which determine ***how many*** threadblocks can be hosted, e.g. shared memory used per threadblock, threads per threadblock, registers used per threadblock, cannot be determined until compile time.

Furthermore, different hardwares have vastly different threadblock hosting capabilities, and being able to ***oversubscribe*** the GPU with threadblocks allows you to be compatible with more hardware. For example, my 2080 Super has only 48 SM's with 64 KB of shared memory. The 4080 has 76 SM's with 128 KB of shared memory. If I wrote my code so that I only ever used 48 threadblocks, the performance would be worse on the 4080 because we wouldn't use all of its available compute capacity.

So for example, in my implementation I dispatch 256 threadblocks for the kernel, even though this is well above the hosting capacity of my GPU, to ensure it runs well on different hardware.

>though is it really any order of threadgroup scheduling?
>I think it is reasonable to launch threadgroups more or less serially, at least in terms of data caching so why would vendors implement that much of a random scheduling?

I can't give an answer as to *why* scheduling is random, but you can convince yourself that the ordering *is* random with the following example: 

```HLSL
globallycoherent RWBuffer<uint> b_index;
RWBuffer<uint> b_threadBlockID;
[numthreads(1,1,1)]
void Example(int3 threadBlockID : SV_GroupID)
{
    int executionOrder;
    InterlockedAdd(b_index[0], 1, executionOrder);
    b_threadBlockID[executionOrder] = threadBlockID.x;
}
```

Similarly to *Chained Scan with Decoupled Lookback*, upon execution each threadblock atomically fetch and adds `b_index`. Then it uses the fetched value as the index to write its `threadBlockID` into `b_threadBlockID`. Running this, we get various different orderings of `threadBlockID` showing that the scheduling is indeed random.
